name: JCB Tests

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  jcb_coding_tests:

    name: Coding Norms
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Make sure python is up to date
        run: |
          pip install --upgrade pip

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install the code
        run: |
          cd $GITHUB_WORKSPACE
          pip install .[testing]

      - name: Run flake8 coding norms
        run: |
          cd $GITHUB_WORKSPACE
          flake8


  jcb_unit_tests:

    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Make sure python is up to date
        run: |
          pip install --upgrade pip

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install the code
        run: |
          cd $GITHUB_WORKSPACE
          pip install pyyaml
          git branch
          ./jcb_client_init.py
          pip install .[testing]

      - name: Run unit tests
        run: |
          cd $GITHUB_WORKSPACE
          pytest -v
